name: build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            ghc: ghc-8.4
            continue-on-error: false
          - os: windows-latest
            ghc: ghc-8.6
            continue-on-error: false
          - os: windows-latest
            ghc: ghc-8.8
            continue-on-error: true
          - os: windows-latest
            ghc: nightly
            continue-on-error: true
          - os: macos-latest
            ghc: ghc-8.4
            continue-on-error: false
          - os: macos-latest
            ghc: ghc-8.6
            continue-on-error: false
          - os: macos-latest
            ghc: ghc-8.8
            continue-on-error: false
          - os: macos-latest
            ghc: nightly
            continue-on-error: true
          - os: ubuntu-latest
            ghc: ghc-8.4
            continue-on-error: false
          - os: ubuntu-latest
            ghc: ghc-8.6
            continue-on-error: false
          - os: ubuntu-latest
            ghc: ghc-8.8
            continue-on-error: false
          - os: ubuntu-latest
            ghc: nightly
            continue-on-error: true

    runs-on: ${{ matrix.os }}

    continue-on-error: ${{ matrix.continue-on-error }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          enable-stack: true
          stack-version: 'latest'
      - uses: actions/cache@v2
        with:
          path: .stack-work
          key: project-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('src') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles(format('stack-{0}.yaml.lock', matrix.ghc)) }}
      - uses: actions/cache@v2
        with:
          path: ~/.stack
          key: user-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('package.yaml') }}-${{ hashFiles(format('stack-{0}.yaml.lock', matrix.ghc)) }}
      - run: make build-deps-${{ matrix.ghc }}
      - run: make build-${{ matrix.ghc }}
